### ISSUE TITLE
IsDiagonalMatrix problem

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/cryst#13]
Some recent changes in the master branch broke Cryst tests - see  https://travis-ci.org/gap-infra/gap-docker-pkg-tests-master/jobs/575655351 

```
#######> Diff in /home/gap/inst/gap-master/pkg/cryst/tst/zass.tst:5
# Input is:
List( List( [1..17], i -> SpaceGroupIT( 2, i ) ),
            g -> Length( SpaceGroupsByPointGroup( PointGroup( g ) ) ) );
# Expected output:
[ 1, 1, 2, 2, 2, 4, 4, 4, 4, 1, 2, 2, 1, 1, 1, 1, 1 ]
# But found:
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `IsDiagonalMatrix' on 1 arguments
########
```
This should be investigated, to decide if changes are required in the core system or in Cryst.

**Comment by gaehler** [comment]
The problem is, that an empty list no longer qualifies as legal input to IsDiagonalMat. An empty matrix object would, but an empty list is something different. There may be quite a few places in cryst where this problem is hit.

**Comment by alex-konovalov** [comment]
Thanks. The fix looks good to me, as it should still work in older GAP versions.

**Comment by alex-konovalov** [comment]
@gaehler works in stable-4.10 branch as well (https://travis-ci.org/gap-infra/gap-docker-pkg-tests-stable-4.10-devel/jobs/576464876). Publishing a new release before GAP 4.11 will be great.

**Comment by gaehler** [comment]
I just realize that the release of GAP 4.11 is due on September 1. Is this still true? If I make a new release of cryst today, would it still get into 4.11? If not, I would not rush and address a different issue with Wyckoff positions first.

**Comment by alex-konovalov** [comment]
@gaehler it's a target date, and we did not even branched off stable-4.11 branch, so please go ahead! I will update now the intended date to 1/11/19.
