### ISSUE TITLE
Tests time out in master branch

### ISSUE THREAD

**Issue by alex-konovalov** [gap-packages/cryst#14]
With the new version, tests for Cryst when GAP is loaded with `-A` option run forever: the test log shows this and does 
```
Testing cryst 4.1.20, test=/circa/scratch/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/32build/GAPTARGET/packages/label/kovacs/GAP-master-snapshot/pkg/cryst/tst/testall.g, all packages=false
Build timed out (after 900 minutes). Marking the build as aborted.
Build was aborted
```
One can try to reproduce this with

    make testpackage PKGNAME=cryst

**Comment by alex-konovalov** [comment]
Reported in https://github.com/gap-system/gap/issues/3670 - there is some change in master branch causing this.

**Comment by gaehler** [comment]
The function MaximalSubgroupRepsSG produces a discrepancy, which later on leads to trouble (wrong results, infinite orbits). This can be reproduced as follows. First, construct this FpGroup:
```
G := SpaceGroupIT( 3, 208 );
p := 3;
F := Image( IsomorphismFpGroup( G ) );
Frels := RelatorsOfFpGroup( F );
Ffree := FreeGroupOfFpGroup( F );
Fgens := GeneratorsOfGroup( Ffree );
gens := List( [5..7], x -> Fgens[x]^p );
F := Ffree / Concatenation( Frels, gens );
```
Now, convert it into a PcGroup, and compute pcgs in different orders. On master, we get:
```
gap> A := PcGroupFpGroup( F );
<pc group of size 648 with 7 generators>
gap> SpecialPcgs( A );
Pcgs([ f1*f3*f4*f5^2*f6*f7, f2*f4*f5*f6^2*f7^2, f3*f4*f5*f7, f4*f5, f5^2*f7, 
  f6*f7^2, f7 ])
gap> Pcgs( A );
Pcgs([ f1*f3*f4*f5^2*f6*f7, f2*f4*f5*f6^2*f7^2, f3*f4*f5*f7, f4*f5, f5^2*f7, 
  f6*f7^2, f7 ])
gap> A := PcGroupFpGroup( F );
<pc group of size 648 with 7 generators>
gap> Pcgs( A );
Pcgs([ f1, f2, f3, f4, f5, f6, f7 ])
gap> SpecialPcgs( A );
Pcgs([ f1*f3*f4*f5^2*f6*f7, f2*f4*f5*f6^2*f7^2, f3*f4*f5*f7, f4*f5, f5^2*f7, 
  f6*f7^2, f7 ])
gap> Pcgs( A );
Pcgs([ f1, f2, f3, f4, f5, f6, f7 ])

```
whereas on 4.10.2 we get
```
gap> A := PcGroupFpGroup( F );
<pc group of size 648 with 7 generators>
gap> SpecialPcgs( A );
Pcgs([ f1*f3*f4*f5^2*f6*f7, f2*f4*f5*f6^2*f7^2, f3*f4*f5*f7, f4*f5, f5^2*f7, 
  f6*f7^2, f7 ])
gap> Pcgs( A );
Pcgs([ f1, f2, f3, f4, f5, f6, f7 ])
gap> 
gap> A := PcGroupFpGroup( F );
<pc group of size 648 with 7 generators>
gap> Pcgs( A );
Pcgs([ f1, f2, f3, f4, f5, f6, f7 ])
gap> SpecialPcgs( A );
Pcgs([ f1*f3*f4*f5^2*f6*f7, f2*f4*f5*f6^2*f7^2, f3*f4*f5*f7, f4*f5, f5^2*f7, 
  f6*f7^2, f7 ])
gap> Pcgs( A );
Pcgs([ f1, f2, f3, f4, f5, f6, f7 ])

```
Cryst silently assumes that Pcgs(A) always produces the simple pcgs, even if first a SpecialPcgs had been computed. I can of course first call Pcgs, but the question is whether this change of behaviour is wanted.

**Comment by fingolfin** [comment]
Regardless of whether or not the behaviour change is wanted, this is a bug in cryst -- making such assumptions on the return value of `Pcgs` is wrong.

Back to the behavior change: Well, the changed code certainly always had the *intention* of leading to behavior as is present in GAP master branch (looking at https://github.com/gap-system/gap/commit/0c67c5af7e75fdbc5cf94628bcdd2d4141538dd5, there is an explicit `SetPcgs` call in there). The code was buggy, and hence the effect never took. Now one might argue that the behavior has been "broken" for so long that the behavior up to 4.10 should now be considered the "expected". But I am not sure this is such a great idea; after all, I can still construct a copy of the group with a different Pcgs, by some other means, and then still the above problem occurs.

All in all, I have a neutral position on whether or not to revert the change on the GAP side (I'd recommend discussing that on https://github.com/gap-system/gap/issues/3670, not here). But again, I also believe that this is a bug in cryst, which also should be fixed.

**Comment by gaehler** [comment]
I agree that silently assuming that Pcgs returns a particular pcgs is dangerous. In our case, the original FpGroup is constructed with a carefully crafted generating set which is already polycyclic. When calling Pcgs, we want a pcgs with this generating set back. For the moment, I can achieve this by calling Pcgs before SpecialPcgs, but I am not sure whether this is safe for the future. Is there a safe way to get this particular pcgs?

**Comment by alex-konovalov** [comment]
This causes tailbacks in regular Jenkins tests, would be nice to resolve before too long - needed for GAP 4.11.
```
Testing cryst 4.1.20, test=/circa/scratch/gap-jenkins/workspace/GAP-master-test/GAPCOPTS/32build/GAPTARGET/packages/label/kovacs/GAP-master-snapshot/pkg/cryst/tst/testall.g, all packages=false
Build timed out (after 900 minutes). Marking the build as aborted.
Build was aborted
```

**Comment by alex-konovalov** [comment]
Picked up an update - let's see! Thanks
```
* Cryst - new version 4.1.21 discovered!!!
  ============================================
  Getting new archives from 
  https://www.math.uni-bielefeld.de/~gaehler/gap45/Cryst/cryst-4.1.21
[ ".tar.gz" ]
  unpacking cryst-4.1.21.tar.gz
  Validation of the info file successful!
  Package Cryst 4.1.21 from 24/10/2019 has dependencies:
  * NeededOtherPackages [ [ "polycyclic", ">=2.9" ] ]
  * GAP >=4.5
  * SuggestedOtherPackages 
[ [ "CrystCat", ">=1.1.4" ], [ "Carat", ">=2.1.1" ], [ "XGAP", ">=4.22" ] ]
  finding text files  . . .
  using [ "doc/manual.pdf", "doc/manual.dvi" 
 ] from PackageInfo.g as binary files 

=====================text files==========================
cryst/COPYING
cryst/README
cryst/init.g
cryst/read.g
cryst/PackageInfo.g
cryst/doc/introduction.tex
cryst/doc/cryst.tex
cryst/doc/manual.tex
cryst/htm/theindex.htm
cryst/htm/CHAP002.htm
cryst/htm/CHAP001.htm
cryst/htm/chapters.htm
cryst/htm/biblio.htm
cryst/gap/equiv.gi
cryst/gap/max.gd
cryst/gap/cryst2.gi
cryst/gap/zass.gi
cryst/gap/wyckoff.gd
cryst/gap/wyckoff.gi
cryst/gap/hom.gd
cryst/gap/zass.gd
cryst/gap/hom.gi
cryst/gap/pcpgrp.gi
cryst/gap/wygraph.gi
cryst/gap/equiv.gd
cryst/gap/noxgap.gi
cryst/gap/fpgrp.gi
cryst/gap/wypopup.gi
cryst/gap/common.gi
cryst/gap/cryst.gd
cryst/gap/max.gi
cryst/gap/color.gi
cryst/gap/orbstab.gi
cryst/gap/color.gd
cryst/gap/cryst.gi
cryst/grp/spacegrp.gd
cryst/grp/spacegrp.grp
cryst/grp/spacegrp.gi
cryst/tst/manual.tst
cryst/tst/cryst.tst
cryst/tst/subgrp.tst
cryst/tst/testall.g
cryst/tst/zass.tst
cryst/tst/wyckoff.tst

=====================end of the list of text files=======
=====================binary files========================
cryst/Changelog
cryst/doc/manual.lab
cryst/doc/manual.toc
cryst/doc/make_doc
cryst/doc/manual.mst
cryst/doc/manual.six
cryst/doc/manual.pdf
cryst/doc/manual.bbl

=====================end of the list of binary files=====
=====================ignored files=======================

=====================end of the list of ignored files====
```

**Comment by gaehler** [comment]
Has been solved by explicitly choosing the desired PCGS, instead of making silent assumptions about it.
