### ISSUE TITLE
Please separate Tests that use CrystCat

### ISSUE THREAD

**Issue by narc-Ontakac2** [gap-packages/cryst#21]
Some tests use functions from crystcat. As a result running the tests for cryst depends on crystcat which depends on cryst. This is bad for debian packaging, where as a result building gap-cryst requires gap-cryst to be installed.

Since I am packaging gap-cryst I have made a patch that separates the tests using crystcat and only runs them if crystcat can be loaded. You might want to apply it.
[tst-split.txt](https://github.com/gap-packages/cryst/files/5505992/tst-split.txt)

**Comment by alex-konovalov** [comment]
Thanks @narc-Ontakac2 - the patch looks correct to me, if you'd like to submit a PR, please go ahead!
