### ISSUE TITLE
The incorrect space group list generated by SpaceGroupsByPointGroupOnLeft.

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/cryst#34]
See my following testing:

```gap
gap> S:=StandardAffineCrystGroup(SpaceGroupOnLeftIT(3,154));
<matrix group with 5 generators>
gap> P:=PointGroup(S);
Group([ [ [ 0, -1, 0 ], [ 1, -1, 0 ], [ 0, 0, 1 ] ], [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ] ])
gap> pgen:= GeneratorsOfGroup(P);
[ [ [ 0, -1, 0 ], [ 1, -1, 0 ], [ 0, 0, 1 ] ], [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ] ]
gap> d:= DimensionOfMatrixGroup(S) - 1;
3
gap> norm:=Filtered(GeneratorsOfGroup( Normalizer( GL(d, Integers), P ) ), x -> not x in P);
[ [ [ -1, 0, 0 ], [ 0, -1, 0 ], [ 0, 0, -1 ] ], [ [ 1, -1, 0 ], [ 1, 0, 0 ], [ 0, 0, 1 ] ], [ [ -1, 0, 0 ], [ -1, 1, 0 ], [ 0, 0, 1 ] ] ]
gap> ss:=SpaceGroupsByPointGroupOnLeft(P, norm, true);
[ [ <matrix group with 5 generators> ], [ <matrix group with 5 generators>, <matrix group with 5 generators> ] ]
gap> List(ss, Size);
[ 1, 2 ]
```
So, `SpaceGroupsByPointGroupOnLeft` generated 2 isomorphic classes of space groups which have the same point group `P`. But in fact, in this case, the actual number of space groups up to affine isomorphism is 3, as listed [here](https://www.cryst.ehu.es/cgi-bin/cryst/programs/nph-kv-list):

![image](https://user-images.githubusercontent.com/11155854/213631264-a8b1c7ae-8d4d-4f6e-a716-146eba7a0568.png)

And it can also be confirmed as follows:

```gap
gap> lst:=Filtered( [150..154], i -> RepresentativeAction( GL(d, Integers),  P, PointGroup(StandardAffineCrystGroup(SpaceGroupOnLeftIT(3,i))) ) <> fail );
[ 150, 152, 154 ]
```
So, it's obvious that the result given by `SpaceGroupsByPointGroupOnLeft` is only a part of the above list:

```gap
gap> List(ss, x -> First( lst, i -> ConjugatorSpaceGroups(First(x), SpaceGroupOnLeftIT(3,i) ) <> fail ) );
[ 150, 152 ]
```

I further tested as follows, but the result is still the same as above:
```gap
gap> P:=PointGroup(StandardAffineCrystGroup(SpaceGroupOnLeftIT(3,154)));
Group([ [ [ 0, -1, 0 ], [ 1, -1, 0 ], [ 0, 0, 1 ] ], [ [ 0, 1, 0 ], [ 1, 0, 0 ], [ 0, 0, -1 ] ] ])
gap> ss:=SpaceGroupsByPointGroupOnLeft(P);
[ <matrix group with 5 generators>, <matrix group with 5 generators>, <matrix group with 5 generators> ]
gap> lst:=Filtered( [150..154], i -> RepresentativeAction( GL(d, Integers),  P, PointGroup(StandardAffineCrystGroup(SpaceGroupOnLeftIT(3,i))) ) <> fail );
[ 150, 152, 154 ]
gap> List(ss, x -> First( lst, i -> ConjugatorSpaceGroups(x, SpaceGroupOnLeftIT(3,i) ) <> fail ) );
[ 150, 152, 152 ]
```

**Comment by gaehler** [comment]
This is no error. Space groups 152 and 154 form an [enantiomorphic pair](http://www.aflowlib.org/prototype-encyclopedia/enantiomorph_info.html) - they are mirror images of each other. They are conjugate, but only with a transformation with negative determinant:

    gap> ConjugatorSpaceGroups( SpaceGroupOnLeftIT(3,152), SpaceGroupOnLeftIT(3,154) );
    [ [ -1, 0, 0, 0 ], [ 0, -1, 0, 0 ], [ 0, 0, -1, 0 ], [ 0, 0, 0, 1 ] ]
    gap> DeterminantMat(last);
    -1

Counting such mirror pairs as one space group results in 219 space group types, whereas counting them separately yields 230 space group types.

**Comment by hongyi-zhao** [comment]
Thank you for pointing this out.

Side remark: Have you also noticed my discussion [here](https://github.com/gap-packages/cryst/pull/33#issuecomment-1396956501)?

**Comment by gaehler** [comment]
gap> S := List( [212,213], i -> SpaceGroupOnLeftIT(3,i));
    gap> conj := ConjugatorSpaceGroups( S[1], S[2] );
    [ [ 0, 0, 1, 1/2 ], [ -1, 0, 0, 0 ], [ 0, 1, 0, 0 ], [ 0, 0, 0, 1 ] ]
    gap> S[1] = S[2]^conj;
    true
    gap> S[2] = S[1]^conj;
    true
    gap> S[1] = S[1]^(conj^2);
    true

`conj^2` acts as an inner automorphim on `S[1]`, but is not the identity.

**Comment by hongyi-zhao** [comment]
I've just updated my algorithm on the enantiomorphic pair determination based on the characteristic of the conjugator.
