### ISSUE TITLE
Affine crystallographic groups vs space groups

### ISSUE THREAD

**Issue by hongyi-zhao** [gap-packages/cryst#36]
I noticed the following description [here](https://github.com/gap-packages/cryst#readme):

> Cryst provides a rich set of methods to compute with affine crystallographic groups, in particular space groups.

For a long time, I have been puzzled by the subtle differences and connections between the two terms: Affine crystallographic groups and space groups. So, what are the differences and connections between them?

Regards,
Zhao

**Comment by gaehler** [comment]
Space groups have a translation subgroup of full rank d, whereas general affine crystallographic groups may have a translation subgroup of smaller rank.
