### ISSUE TITLE
VectorModL for non-orthogonal lattice

### ISSUE THREAD

**Issue by kiryph** [gap-packages/cryst#50]
```gap
gap> L := [ [ 1, 2 ], [ 0, 3 ] ];;
gap> L[1] * L[2] <> 0; # non-orthogonal
true
gap> pnt := [1/2, 1/2];;
gap> VectorModL(pnt, L);
[ 1/2, 1/2 ]
```

This is not what I expect, but

```gap
gap> MyVectorModL := function(pnt, L)
>   return VectorModL(pnt * Inverse(L), IdentityMat(Length(pnt))) * L;
> end;;
gap> MyVectorModL(pnt, L);
[ 1/2, 7/2 ]
```

**Comment by bfield1** [comment]
I suppose one challenge here is that the translation basis is not guaranteed to span the whole space (i.e. in sub-periodic groups), so one cannot simply take the inverse of L. v is not guaranteed to be in the span of L either, so one cannot solve the linear system to get v in fractional coordinates of L either.

Also, `VectorModL` is undocumented, so we aren't promised any specific functionality. Making the behaviour more intuitive (e.g. taking v to the region bounded by L) would likely incur some computational overhead when they generally only need consistency for a given L.

**Comment by kiryph** [comment]
@bfield1 Thanks for your answer.

> I suppose one challenge here is that the translation basis is not guaranteed to span the whole space (i.e. in sub-periodic groups), so one cannot simply take the inverse of L. v is not guaranteed to be in the span of L either, so one cannot solve the linear system to get v in fractional coordinates of L either.

That is true. Here I would indeed specialize code and introduce a `VectorModSubL` which applies the modulo operation only in a subspace (for plane and space groups: planes or lines).

> Also, `VectorModL` is undocumented, so we aren't promised any specific functionality.

I am not yet sure if this issue is already a problem for the current code.

`VectorModL` is used, e.g. in following methods

- `RepresentativeActionOp` for AffineCrystGroups
- `\in( m, S )`

and non-orthogonal lattices are allowed to be used.

> Making the behaviour more intuitive (e.g. taking v to the region bounded by L) would likely incur some computational overhead when they generally only need consistency for a given L.

What consistency do you mean?

**Comment by gaehler** [comment]
`VectorModL` is an undocumented, internal helper function. `VectorModL(x,L)` returns a unique, standard representative of the coset `x + M`, where `M` is the free Z-module generated by the rows of the matix `L` (which is silently assumed to be in reduced form, as returned by `ReducedTranslationBasis`). I think it fulfills this task, and didn't promise anything else.

**Comment by kiryph** [comment]
Thanks for your feedback and clarification. I'll close the issue.

Even though I think a more sensible name could have been chosen, even for an undocumented function: `VectorModL` suggests that the vector is taken modulo `L` and in my book this is not the case for non-orthogonal lattices. And the method is not `VectorModOne` (which is contained, e.g. in HAPCryst).
